# Contains all the constants for the project.
NUM_TILE_TYPES = 46
NUM_PLAYABLE_TILE_TYPES = 34

# Mapping of mahjong tiles to list indices
# Characters (WAN)
CHARACTERS_1 = 0
CHARACTERS_2 = 1
CHARACTERS_3 = 2
CHARACTERS_4 = 3
CHARACTERS_5 = 4
CHARACTERS_6 = 5
CHARACTERS_7 = 6
CHARACTERS_8 = 7
CHARACTERS_9 = 8

# Bamboo (SHUO)
BAMBOO_1 = 9
BAMBOO_2 = 10
BAMBOO_3 = 11
BAMBOO_4 = 12
BAMBOO_5 = 13
BAMBOO_6 = 14
BAMBOO_7 = 15
BAMBOO_8 = 16
BAMBOO_9 = 17

# Dots (TONG)
DOTS_1 = 18
DOTS_2 = 19
DOTS_3 = 20
DOTS_4 = 21
DOTS_5 = 22
DOTS_6 = 23
DOTS_7 = 24
DOTS_8 = 25
DOTS_9 = 26

# Honors (Wind + Dragons)
HONORS_RED = 27
HONORS_WHITE = 28
HONORS_GREEN = 29
HONORS_WEST = 30
HONORS_SOUTH= 31
HONORS_EAST = 32
HONORS_NORTH = 33

# Flowers (HUA)
FLOWER_RED_1 = 34 
FLOWER_RED_2 = 35
FLOWER_RED_3 = 36
FLOWER_RED_4 = 37

FLOWER_BLUE_1 = 38
FLOWER_BLUE_2 = 39
FLOWER_BLUE_3 = 40
FLOWER_BLUE_4 = 41

# Animals
CAT = 42
RAT = 43
CHICKEN = 44
CENTIPETE = 45

# Sets
CHARACTER = [CHARACTER_1, CHARACTER_2, CHARACTER_3, CHARACTER_4, CHARACTER_5, CHARACTER_6, CHARACTER_7, CHARACTER_8, CHARACTER_9]
BAMBOO = [BAMBOO_1, BAMBOO_2, BAMBOO_3, BAMBOO_4, BAMBOO_5, BAMBOO_6, BAMBOO_7, BAMBOO_8, BAMBOO_9]
DOTS = [DOTS_1, DOTS_2, DOTS_3, DOTS_4, DOTS_5, DOTS_6, DOTS_7, DOTS_8, DOTS_9]
DRAGONS = [HONOURS_RED, HONOURS_WHITE, HONOURS_GREEN]
WINDS = [HONOURS_WEST, HONOURS_SOUTH, HONOURS_EAST, HONOURS_NORTH]
FLOWERS = [FLOWER_RED_1, FLOWER_RED_2, FLOWER_RED_3, FLOWER_RED_4, FLOWER_BLUE_1, FLOWER_BLUE_2, FLOWER_BLUE_3, FLOWER_BLUE_4]
ANIMALS = [CAT, RAT, CHICKEN, CENTIPETE]
WONDERS = [CHARACTERS_1, CHARACTER_9, BAMBOO_1, BAMBOO_9, DOTS_1, DOTS_9] + DRAGONS + WINDS
NON_PLAYABLE = FLOWERS + ANIMALS
